// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tybfnsmrrnxtinngytqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5YmZuc21ycm54dGlubmd5dHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1Mjk4MzcsImV4cCI6MjA2NjEwNTgzN30.rjSD7N2i0NjVDmWLoU5PMpqT9OSwNQhBCfH4Caq3VYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);